config/routes.rb
Rails.application.routes.draw do
  root 'chatroom#index'
  delete '/logout', to: 'session#destroy'
  get '/login', to: 'session#new'
  post '/login', to: 'session#create'
  resources :messages, only: [:create]
  mount ActionCable.server,at: '/cable'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, length: { minimum: 3, maximum: 15 },
            uniqueness: { case_sensitive: false }
  has_many :messages
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?

    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
      !!current_user
    end

    def require_user
      if !logged_in?
        flash[:error] = "You must be logged in to perform that action"
        redirect_to login_path
      end
    end
    
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
  before_action:require_user

  def index
    @messages = Message.all
    @message = Message.new
    @user=User.all
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_user

  def create
    @message = current_user.messages.build(message_params)
    if @message.save
      flash[:notice] = 'Message created successfully.'
      ActionCable.server.broadcast "chatroom_channel", mod_message: message_render(@message)
    else
      flash[:alert] = 'Failed to create message.'
    end
  end

  private

  def message_params
    params.require(:message).permit(:body)
  end

  def message_render(message)
    render(partial: 'message/message', locals: { message: message })
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    if params[:session].present?
      user = User.find_by(username: params[:session][:username])
      if user && user.authenticate(params[:session][:password])
        session[:user_id] = user.id
        flash[:success] = "You have successfully logged in"
        redirect_to root_path
      else
        flash.now[:error] = "There was something wrong with your login information"
        render 'new'
      end
    else
      flash.now[:error] = "Invalid login information"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have successfully logged out"
    redirect_to login_path
  end

  private

  def logged_in_redirect
    if logged_in?
      flash[:error] = "You are already logged in"
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatroom_helper.rb
module ChatroomHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/chatroom/index.html.erb
<h4 class="ui center aligned medium icon header">
  <i class="circular orange coffee icon"></i>
  Say Something
</h4>

<div class="ui container">
  <div class="col-md-12">
    <div class="ui fluid raised card chatbox">
      <div class="content" id="messages">
        <div class="ui feed" id="message-container">
          <%= render partial: "message/message" , collection: @messages %>

        </div>

        <%= form_for(@message, url: messages_path, remote: true) do |form| %>
          <div class="container">

          </div class="row d-flex">
          <div class="col-md-12">
            <%= form.text_field :body, class: "form-control" %>
          </div>
          <div class="col-md-1" >
            <%= form.submit "Send" , id: "send" %>
          </div>
          <% end %>
          </div>
      </div>

    </div>

    <div class="four wide column">
      <div class="ui fluid raised card chatbox">
        <div class="content">
          <div class="ui inverted vertical menu">
            <a class="active item">
              Home
            </a>
            <a class="item">
              Messages
            </a>
            <a class="item">
              Friends
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageMe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>


    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
     integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  </head>

  <body>
    <div class="ui inverted menu">
      <div class="ui container">
        <a class="active item">
          chatroom
        </a>
        <a class="item">
          Messages
        </a>

        <div class="ui compact inverted right menu">
          <div class="ui simple dropdown item">
            <% if @current_user %>
              <%= @current_user.username %>
              <i class="dropdown icon"></i>
              <div class="menu">
                <%= link_to 'Logout', logout_path, data: {"turbo-method": :delete }, class: 'item' %>
              </div>
            <% else %>
              Accounts
              <i class="dropdown icon"></i>
              <div class="menu">
                <div class="item"><%= link_to 'Login', login_path %></div>
                <div class="item">Sign up</div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>

    <%= yield %>

  </body>
</html>

app/views/message/_message.html.erb
<div class="content ">
  <div class="summary">
   <b> <em><%= message.user.username %></em> : </b> <%= message.body %>
  </div>
</div>

app/views/session/new.html.erb
<h2 class="ui center aligned large header">
    Welcome to MessageMe - <em>a complete Chat App</em>
  </h2>

  <h4 class="ui center aligned medium icon header">
    <i class="circular orange power off tiny icon"></i>
    Log in to continue
  </h4>


  <div class="ui container placeholder segment">
    <div class="ui two column very relaxed stackable grid">
      <div class="column">
        
        <%= form_for(:session, html: {class: "ui form", role: "form"}, url: login_path) do |f| %>
          <div class="field">
            <%= f.label :username, "Username" %>
            <div class="ui left icon input">
              <%= f.text_field :username, placeholder: "Username" %>
              <i class="user icon"></i>
            </div>
          </div>
          <div class="field">
            <%= f.label :password, "Password" %>
            <div class="ui left icon input">
              <%= f.password_field :password, placeholder: "Password" %>
              <i class="lock icon"></i>
            </div>
          </div>
          <%= f.button "Login", class: "ui orange submit button" %>
        <% end %>
      </div>
      <div class="middle aligned column">
        <div class="ui big orange disabled button">
          <i class="signup icon"></i>
          Sign Up
        </div>
      </div>
    </div>
    <div class="ui vertical divider">
      Or
    </div>
  </div>